### ISSUE TITLE
FEATURE : Add JSON Syntax Validation to Workflow ⚡

### ISSUE THREAD

**Issue by Nishitbaria** [Opentek-Org/opentek#457]
**Description:**
I would like to suggest an enhancement to the existing workflow "JSON check" to include a step that checks whether the JSON syntax is valid or not. This will help ensure that the JSON files in the repository are correctly formatted and avoid potential issues caused by invalid JSON.

**Workflow:**
```yaml
name: JSON check

on:
  push:
    paths:
      - "**.json"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
      - name: json-validation
        run: |
          # Add a step here to perform JSON syntax validation
          # You can use a tool like `jq` or a custom script to validate the JSON syntax
          # For example, you can use the following command:
          #   jq empty < your_file.json
```

**Explanation:**
The suggested enhancement adds a new step named "json-validation" to the existing workflow. This step performs the JSON syntax validation using a tool like `jq` or a custom script. In the example provided, the `jq` command `jq empty < your_file.json` is used, which checks if the JSON file is empty or not. You can modify this step according to your specific JSON validation requirements.

By incorporating this enhancement into the workflow, you can ensure that the JSON files in the repository are not only checked for syntax errors but also validated against specific criteria, promoting better quality and correctness of the JSON data.

Please consider implementing this enhancement to enhance the functionality of the existing "JSON check" workflow.
