### ISSUE TITLE
[Feat]: Update Dependabot Workflow

### ISSUE THREAD

**Issue by Anmol-Baranwal** [Opentek-Org/opentek#510]
### Is your feature request related to a problem? Please describe.

> Current One

```yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
```

Firstly, it should have a proper commit prefix according to conventions, such as `chore(deps)`. Additionally, it lacks a label, which could be helpful for someone looking at the PR, like `📦 dependencies`.

I will add the changes with detailed instructions and a reference.

### Additional context.

> I will do this contribution under GSSoC'23. 

### Show us the magic with screenshots

Like this: (looks clean and according to conventions)
![image](https://github.com/Opentek-Org/opentek/assets/74038190/7014ee03-1051-453f-8cf4-4509a7ffd750)
